# Generated by Django 5.0.6 on 2024-06-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
    ]
