# Generated by Django 5.0.6 on 2024-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookingapp', '0002_busdetails_delete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='busdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
