# Generated by Django 5.0.6 on 2024-07-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookingapp', '0007_passengerdetailsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengerdetailsforms1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('usernumber', models.CharField(max_length=23)),
                ('useremail', models.CharField(max_length=30)),
                ('userage', models.CharField(max_length=40)),
                ('usergender', models.CharField(max_length=23)),
                ('userchild', models.CharField(max_length=40)),
                ('userid', models.CharField(max_length=23)),
                ('userboardingpoint', models.CharField(max_length=30)),
                ('userdropingpoint', models.CharField(max_length=40)),
                ('useridtype', models.CharField(max_length=23)),
                ('userseat', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='passengerdetailsform',
        ),
    ]
