# Generated by Django 5.0.6 on 2024-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookingapp', '0008_passengerdetailsforms1_delete_passengerdetailsform'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('useremail', models.CharField(max_length=30)),
                ('usernumber', models.CharField(max_length=23)),
            ],
        ),
    ]
