# Generated by Django 5.0.6 on 2024-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busbookingapp', '0009_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingselection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('CHENNAI', 'Chennai'), ('COIMBATORE', 'Coimbatore'), ('MADURAI', 'Madurai'), ('TIRUCHY', 'Tiruchy'), ('DHARAPURAM', 'Dharapuram')], max_length=20)),
                ('destination', models.CharField(choices=[('CHENNAI', 'Chennai'), ('COIMBATORE', 'Coimbatore'), ('MADURAI', 'Madurai'), ('TIRUCHY', 'Tiruchy'), ('DHARAPURAM', 'Dharapuram')], max_length=20)),
                ('passengers', models.PositiveIntegerField()),
                ('depart', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
